import { useEffect, useState } from 'react';
import { MapContainer, ImageOverlay, Marker, Tooltip } from 'react-leaflet';
import L, { LatLngBoundsExpression } from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {
  Box,
  Chip,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Typography,
  useTheme,
} from '@mui/material';
import StorefrontIcon from '@mui/icons-material/Storefront';
import api from '../../api/api';
import type { Vendor } from '../../models/vendors';

// ── Per-zoom actual image dimensions [width, height] ────────────────────────
// Generated by stitch_images.py from CloudFront tiles (256px each):
//   z3: 8×8 tiles   → 2048×2048
//   z4: 16×16       → 4096×4096
//   z5: 32×32       → 8192×8192
//   z6: 64×51 tiles → 16384×13056
//   z7: 128×65 tiles→ 32768×16640
const IMAGE_DIMS: Record<number, [number, number]> = {
  3: [2048, 2048],
  4: [4096, 4096],
  5: [8192, 8192],
  6: [16384, 13056],
  7: [32768, 16640],
};

// Vendor map_x / map_y are tile coordinates at z7 (lg/lt from the Gen Con
// exhibitors API).  Dividing by the z7 tile counts [128, 65] makes the scale
// factor 256 px/tile at z7 and propagates correctly to every other zoom level.
const BASE_DIMS: [number, number] = [128, 65];

const FLOORS = [
  { key: 'floor-0', label: 'Basement' },
  { key: 'floor-1', label: 'First Floor' },
  { key: 'floor-2', label: 'Second Floor' },
  { key: 'floor-3', label: 'Third Floor' },
  { key: 'floor-4', label: 'Fourth Floor' },
];

const ZOOM_LABELS: Record<number, string> = {
  3: 'Low (fast)',
  4: 'Medium',
  5: 'High',
  6: 'Very high',
  7: 'Max (slow)',
};

// ── Vendor pin as a div icon ────────────────────────────────────────────────
function vendorIcon(label: string) {
  return L.divIcon({
    className: '',
    html: `<div style="
      background:#f59e0b;
      color:#111827;
      font-size:10px;
      font-weight:700;
      line-height:1;
      padding:3px 6px;
      border-radius:4px;
      white-space:nowrap;
      box-shadow:0 1px 6px rgba(0,0,0,0.6);
      font-family:'Inter',Arial,sans-serif;
      cursor:pointer;
    ">${label}</div>`,
    iconAnchor: [0, 0],
  });
}

export default function GenConMap() {
  const theme = useTheme();
  const [currentFloor, setCurrentFloor] = useState('floor-1');
  const [imageZoom, setImageZoom] = useState(4);
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [showVendors, setShowVendors] = useState(true);

  // ── Fetch all vendors that have map coordinates ──────────────────────────
  useEffect(() => {
    const fetchAll = async () => {
      try {
        let all: Vendor[] = [];
        let url = '/vendors/';
        while (url) {
          const res = await api.get(url);
          all = [...all, ...res.data.results];
          url = res.data.next ?? null;
        }
        setVendors(all.filter((v) => v.mapX != null && v.mapY != null));
      } catch (err) {
        console.error('Failed to load vendors for map', err);
      }
    };
    fetchAll();
  }, []);

  const STATIC_URL = import.meta.env.DEV ? 'http://localhost:8000/static' : '/static';

  const [imgW, imgH] = IMAGE_DIMS[imageZoom];

  // ── Correct CRS.Simple bounds ────────────────────────────────────────────
  // Leaflet CRS.Simple: lat/Y increases UPWARD. PNG pixels: Y increases DOWN.
  // Map pixel (px, py) → Leaflet position [-py * scaleY, px * scaleX]
  // Bounds: bottom-left corner = [-imgH, 0], top-right = [0, imgW]
  const bounds: LatLngBoundsExpression = [[-imgH, 0], [0, imgW]];

  const [baseW, baseH] = BASE_DIMS;
  const scaleX = imgW / baseW;
  const scaleY = imgH / baseH;

  const mappedVendors = showVendors ? vendors : [];

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 80px)' }}>

      {/* ── Controls bar ──────────────────────────────────────────────────── */}
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          gap: 2,
          px: 2,
          py: 1.5,
          flexShrink: 0,
          bgcolor: 'background.paper',
          borderBottom: `1px solid ${theme.palette.divider}`,
          flexWrap: 'wrap',
        }}
      >
        <FormControl size="small" sx={{ minWidth: 140 }}>
          <InputLabel>Floor</InputLabel>
          <Select
            value={currentFloor}
            label="Floor"
            onChange={(e) => setCurrentFloor(e.target.value)}
          >
            {FLOORS.map((f) => (
              <MenuItem key={f.key} value={f.key}>{f.label}</MenuItem>
            ))}
          </Select>
        </FormControl>

        <FormControl size="small" sx={{ minWidth: 140 }}>
          <InputLabel>Resolution</InputLabel>
          <Select
            value={imageZoom}
            label="Resolution"
            onChange={(e) => setImageZoom(Number(e.target.value))}
          >
            {Object.entries(ZOOM_LABELS).map(([z, label]) => (
              <MenuItem key={z} value={Number(z)}>{label}</MenuItem>
            ))}
          </Select>
        </FormControl>

        <Chip
          icon={<StorefrontIcon fontSize="small" />}
          label={`Vendors (${vendors.length})`}
          color={showVendors ? 'primary' : 'default'}
          variant={showVendors ? 'filled' : 'outlined'}
          onClick={() => setShowVendors((v) => !v)}
          sx={{ cursor: 'pointer' }}
        />

        <Typography variant="caption" color="text.secondary" sx={{ ml: 'auto' }}>
          {imgW.toLocaleString()} × {imgH.toLocaleString()} px · scroll to zoom · drag to pan
        </Typography>
      </Box>

      {/* ── Map ───────────────────────────────────────────────────────────── */}
      <Box sx={{ flexGrow: 1, position: 'relative', bgcolor: '#0f172a' }}>
        {/*
          key={`${currentFloor}-${imageZoom}`} forces a full MapContainer
          re-mount when floor or zoom changes. Without this, Leaflet won't
          update its internal bounds when the image dimensions change.
        */}
        <MapContainer
          key={`${currentFloor}-${imageZoom}`}
          crs={L.CRS.Simple}
          bounds={bounds}
          scrollWheelZoom={true}
          attributionControl={false}
          zoomControl={true}
          style={{ height: '100%', width: '100%', background: '#0f172a' }}
        >
          <ImageOverlay
            url={`${STATIC_URL}/stitched/${currentFloor}_z${imageZoom}.png`}
            bounds={bounds}
            opacity={1}
            zIndex={0}
          />

          {/* Vendor pins */}
          {mappedVendors.map((v) => {
            // Scale from z7 pixel coords to current image coords, then flip Y
            const lat = -(v.mapY! * scaleY);
            const lng = v.mapX! * scaleX;
            const pinLabel = v.booth_number ?? v.name.slice(0, 8);

            return (
              <Marker
                key={v.gencon_id}
                position={[lat, lng]}
                icon={vendorIcon(pinLabel)}
              >
                <Tooltip
                  direction="top"
                  offset={[0, -4]}
                  opacity={1}
                  className="alpha-vendor-tooltip"
                >
                  <span style={{ fontFamily: 'Inter, Arial, sans-serif', fontSize: 12 }}>
                    <strong>{v.name}</strong>
                    {v.booth_number && <><br />Booth {v.booth_number}</>}
                  </span>
                </Tooltip>
              </Marker>
            );
          })}
        </MapContainer>
      </Box>
    </Box>
  );
}
