import { useEffect, useRef, useState } from 'react';
import { MapContainer, ImageOverlay, Marker, Tooltip, Polygon, Polyline, useMap, useMapEvents } from 'react-leaflet';
import L, { LatLngBoundsExpression } from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {
  Box,
  Chip,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Typography,
  useTheme,
} from '@mui/material';
import StorefrontIcon from '@mui/icons-material/Storefront';
import MeetingRoomIcon from '@mui/icons-material/MeetingRoom';
import MyLocationIcon from '@mui/icons-material/MyLocation';
import ExitToAppIcon from '@mui/icons-material/ExitToApp';
import AltRouteIcon from '@mui/icons-material/AltRoute';
import EventIcon from '@mui/icons-material/Event';
import api from '../../api/api';
import type { Vendor } from '../../models/vendors';
import type { Room } from '../../models/rooms';

// ── Purchased event (from user_events API) ───────────────────────────────────
interface PurchasedEvent {
  id: number;
  event_title: string;
  event_game_id: string;
  event_location: string;
  event_room: string | null;
  event_start_time: string;
  // Room-level Gen Con map coords (precise, floor-specific)
  room_map_lng: number | null;
  room_map_lat: number | null;
  room_map_floor: number | null;
  // Location-level real-world coords (building fallback, no floor)
  event_longitude: number | null;
  event_latitude: number | null;
  status: string;
}

// Resolve the best available coordinates for a purchased event.
// Returns { lng, lat, floorSpecific } — floorSpecific=false means show on all floors.
function resolveEventCoords(ev: PurchasedEvent): { lng: number; lat: number; floor: number | null } | null {
  if (ev.room_map_lng != null && ev.room_map_lat != null) {
    return { lng: ev.room_map_lng, lat: ev.room_map_lat, floor: ev.room_map_floor };
  }
  if (ev.event_longitude != null && ev.event_latitude != null) {
    return { lng: ev.event_longitude, lat: ev.event_latitude, floor: null }; // null = show on all floors
  }
  return null;
}

// ── Per-zoom actual image dimensions [width, height] ────────────────────────
// Generated by stitch_images.py from CloudFront tiles (256px each):
//   z3: 8×8 tiles   → 2048×2048
//   z4: 16×16       → 4096×4096
//   z5: 32×32       → 8192×8192
//   z6: 64×51 tiles → 16384×13056
//   z7: 128×65 tiles→ 32768×16640
const IMAGE_DIMS: Record<number, [number, number]> = {
  3: [2048, 2048],
  4: [4096, 4096],
  5: [8192, 8192],
  6: [16384, 13056],
  7: [32768, 16640],
};

// Vendor map_x = longitude (−180 to +180) and map_y = latitude (−85.051 to
// +85.051) in Web Mercator geographic coordinates, confirmed by the
// geo_elements API corner requests: the full floor-1 map spans exactly the
// Web Mercator world limits.
//
// Pixel conversion uses Web Mercator projection (NOT linear):
//   pixel_x = (lng + 180) / 360 × imgW
//   pixel_y = (1 − ln(tan(π/4 + lat_rad/2)) / π) / 2 × imgW
//
// imgW (= 2^z × 256) is the full-world pixel width at every zoom level.
// imgH may be truncated at z6-z7 (southern hemisphere tiles absent), so we
// always use imgW as the Mercator world extent for both axes.
//
// Leaflet CRS.Simple: lng_leaflet = pixel_x; lat_leaflet = −pixel_y.

const FLOORS = [
  { key: 'floor-0', label: 'Basement' },
  { key: 'floor-1', label: 'First Floor' },
  { key: 'floor-2', label: 'Second Floor' },
  { key: 'floor-3', label: 'Third Floor' },
  { key: 'floor-4', label: 'Fourth Floor' },
];

const ZOOM_LABELS: Record<number, string> = {
  3: 'Low (fast)',
  4: 'Medium',
  5: 'High',
  6: 'Very high',
  7: 'Max (slow)',
};

// ── Auto-resolution thresholds ───────────────────────────────────────────────
// When Leaflet zoom >= UPGRADE_AT[imageZoom], bump imageZoom up one step.
// When Leaflet zoom <= DOWNGRADE_AT[imageZoom], drop imageZoom down one step.
// Hysteresis gap prevents thrashing at the boundary.
const UPGRADE_AT: Partial<Record<number, number>> = { 3: 0, 4: 1, 5: 2, 6: 3 };
const DOWNGRADE_AT: Partial<Record<number, number>> = { 4: -3, 5: -2, 6: -1, 7: 0 };

// Integer zoom steps offered in the Map Zoom dropdown
const MAP_ZOOM_STEPS = [-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4];

// ── Shared Web Mercator → Leaflet coordinate conversion ─────────────────────
function toLeafletPos(lng: number, lat: number, imgW: number): [number, number] {
  const lat_rad = lat * Math.PI / 180;
  const yMercator = Math.log(Math.tan(Math.PI / 4 + lat_rad / 2));
  const pixelY = (1 - yMercator / Math.PI) / 2 * imgW;
  const pixelX = (lng + 180) / 360 * imgW;
  return [-pixelY, pixelX];
}

// ── Convert a booth polygon [[lng, lat], ...] to Leaflet positions ───────────
function toLeafletPolygon(polygon: [number, number][], imgW: number): [number, number][] {
  return polygon.map(([lng, lat]) => toLeafletPos(lng, lat, imgW));
}

// ── Inverse Web Mercator: Leaflet pixel coords → Gen Con map lng/lat ─────────
// Leaflet CRS.Simple gives us pixel coords as [lat=-pixelY, lng=pixelX].
// Reverse the projection to recover Gen Con map_x (lng) and map_y (lat).
function fromLeafletPos(leafletLat: number, leafletLng: number, imgW: number) {
  const pixelX = leafletLng;
  const pixelY = -leafletLat;
  const gencon_lng = pixelX / imgW * 360 - 180;
  const mercatorY = Math.PI * (1 - 2 * pixelY / imgW);
  const gencon_lat = (2 * Math.atan(Math.exp(mercatorY)) - Math.PI / 2) * 180 / Math.PI;
  return { gencon_lng, gencon_lat };
}

// ── Route types ──────────────────────────────────────────────────────────────
interface RouteNode { node_id: string; label: string; }
interface RouteSegment {
  from_label: string; to_label: string;
  from_lng: number;   from_lat: number;
  to_lng: number;     to_lat: number;
  edge_type: 'indoor' | 'outdoor' | string;
  metres: number;
}
interface RouteResult {
  from_node: string; to_node: string;
  total_metres: number;
  segments: RouteSegment[];
}

// ── Combined map event handler ───────────────────────────────────────────────
// Handles coordinate picking, zoom/move tracking, and view restoration after
// imageZoom-triggered remounts.
interface PickResult { gencon_lng: number; gencon_lat: number; }

function MapEventHandler({
  active,
  imgW,
  onPick,
  onMapChange,
  mapRef,
  savedViewRef,
}: {
  active: boolean;
  imgW: number;
  onPick: (r: PickResult) => void;
  onMapChange: (zoom: number, center: [number, number]) => void;
  mapRef: React.MutableRefObject<L.Map | null>;
  savedViewRef: React.MutableRefObject<{ gencon_lng: number; gencon_lat: number; zoom: number } | null>;
}) {
  const map = useMap();

  // On mount: store map ref and restore saved position if present.
  // Empty deps intentional — runs once per MapContainer lifecycle.
  useEffect(() => {
    mapRef.current = map;
    const sv = savedViewRef.current;
    if (sv) {
      savedViewRef.current = null;
      const [lat, lng] = toLeafletPos(sv.gencon_lng, sv.gencon_lat, imgW);
      map.setView([lat, lng], sv.zoom, { animate: false });
    }
    return () => { mapRef.current = null; };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useMapEvents({
    click(e) {
      if (!active) return;
      const result = fromLeafletPos(e.latlng.lat, e.latlng.lng, imgW);
      onPick(result);
    },
    zoomend() {
      onMapChange(map.getZoom(), [map.getCenter().lat, map.getCenter().lng]);
    },
    moveend() {
      onMapChange(map.getZoom(), [map.getCenter().lat, map.getCenter().lng]);
    },
  });
  return null;
}

// ── Vendor pin (amber badge) ─────────────────────────────────────────────────
function vendorIcon(label: string) {
  const iconWidth = Math.max(28, label.length * 7 + 12);
  return L.divIcon({
    className: 'alpha-vendor-pin',
    html: `<div style="
      background:#f59e0b;color:#111827;font-size:10px;font-weight:700;
      line-height:1;padding:3px 6px;border-radius:4px;white-space:nowrap;
      box-shadow:0 1px 6px rgba(0,0,0,0.6);font-family:'Inter',Arial,sans-serif;
      cursor:pointer;
    ">${label}</div>`,
    iconSize: [iconWidth, 20],
    iconAnchor: [iconWidth / 2, 10],
  });
}

// ── Entrance pin (cadetblue badge with ⇒ prefix) ─────────────────────────────
// Label is shortened by stripping common suffixes from the room_name.
function entranceLabel(room_name: string): string {
  return room_name
    .replace(/ Entrance Arrow\s*\d*/i, '')
    .replace(/ Entry Arrow\s*\d*/i, '')
    .replace(/ Arrow\s*\d*/i, '')
    .replace(/ to Hall [A-Z]/i, '')
    .trim();
}

function buildingExitLabel(room_name: string): string {
  return room_name
    .replace(/^ICC\s+/i, '')
    .replace(/\s+Entrance(\s*\([^)]*\))?/i, (_, suffix) => suffix ?? '')
    .replace(/^Skywalk to\s+/i, '↗ ')
    .replace(/\s+Skywalk to\s+/i, ' ↗ ')
    .replace(/\s+Tunnel to\s+/i, ' ↓ ')
    .trim();
}

function buildingExitIcon(label: string) {
  const iconWidth = Math.max(40, label.length * 7 + 22);
  return L.divIcon({
    className: 'alpha-exit-pin',
    html: `<div style="
      background:#c2410c;color:#fff;font-size:10px;font-weight:700;
      line-height:1;padding:3px 7px;border-radius:4px;white-space:nowrap;
      box-shadow:0 1px 6px rgba(0,0,0,0.6);font-family:'Inter',Arial,sans-serif;
      cursor:pointer;
    ">⊕ ${label}</div>`,
    iconSize: [iconWidth, 20],
    iconAnchor: [iconWidth / 2, 10],
  });
}

function entranceIcon(label: string) {
  const iconWidth = Math.max(36, label.length * 7 + 20);
  return L.divIcon({
    className: 'alpha-entrance-pin',
    html: `<div style="
      background:#5f9ea0;color:#fff;font-size:10px;font-weight:700;
      line-height:1;padding:3px 7px;border-radius:4px;white-space:nowrap;
      box-shadow:0 1px 6px rgba(0,0,0,0.6);font-family:'Inter',Arial,sans-serif;
      cursor:pointer;
    ">⇒ ${label}</div>`,
    iconSize: [iconWidth, 20],
    iconAnchor: [iconWidth / 2, 10],
  });
}

// ── Purchased event pin (sky-blue badge) ─────────────────────────────────────
function myEventIcon(label: string) {
  const iconWidth = Math.max(36, label.length * 7 + 22);
  return L.divIcon({
    className: 'alpha-event-pin',
    html: `<div style="
      background:#38bdf8;color:#0c1a2e;font-size:10px;font-weight:700;
      line-height:1;padding:3px 7px;border-radius:4px;white-space:nowrap;
      box-shadow:0 1px 6px rgba(0,0,0,0.7);font-family:'Inter',Arial,sans-serif;
      cursor:pointer;border:1px solid rgba(255,255,255,0.3);
    ">◆ ${label}</div>`,
    iconSize: [iconWidth, 20],
    iconAnchor: [iconWidth / 2, 10],
  });
}

export default function GenConMap() {
  const theme = useTheme();
  const [currentFloor, setCurrentFloor] = useState('floor-1');
  const [imageZoom, setImageZoom] = useState(4);
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [entrances, setEntrances] = useState<Room[]>([]);
  const [buildingExits, setBuildingExits] = useState<Room[]>([]);
  const [showBuildingExits, setShowBuildingExits] = useState(true);
  const [showVendors, setShowVendors] = useState(true);
  const [showEntrances, setShowEntrances] = useState(true);
  const [purchasedEvents, setPurchasedEvents] = useState<PurchasedEvent[]>([]);
  const [showMyEvents, setShowMyEvents] = useState(true);
  const [pickMode, setPickMode] = useState(false);
  const [picked, setPicked] = useState<{ gencon_lng: number; gencon_lat: number } | null>(null);
  const [leafletZoom, setLeafletZoom] = useState<number | null>(null);
  const [leafletCenter, setLeafletCenter] = useState<[number, number] | null>(null);

  // ── Route state ──────────────────────────────────────────────────────────
  const [routeMode, setRouteMode] = useState(false);
  const [routeFrom, setRouteFrom] = useState<RouteNode | null>(null);
  const [routeTo, setRouteTo] = useState<RouteNode | null>(null);
  const [routeResult, setRouteResult] = useState<RouteResult | null>(null);
  const [routeError, setRouteError] = useState<string | null>(null);
  const [routeLoading, setRouteLoading] = useState(false);

  // Stable refs — no re-render on write
  const mapRef = useRef<L.Map | null>(null);
  const savedViewRef = useRef<{ gencon_lng: number; gencon_lat: number; zoom: number } | null>(null);

  // ── Fetch all vendors that have map coordinates ──────────────────────────
  useEffect(() => {
    const fetchAll = async () => {
      try {
        let all: Vendor[] = [];
        let url = '/vendors/';
        while (url) {
          const res = await api.get(url);
          all = [...all, ...res.data.results];
          url = res.data.next ?? null;
        }
        setVendors(all.filter((v) => v.map_x != null && v.map_y != null));
      } catch (err) {
        console.error('Failed to load vendors for map', err);
      }
    };
    fetchAll();
  }, []);

  // ── Fetch entrance rooms (all floors — filter client-side with vendors) ──
  useEffect(() => {
    api.get('/rooms/', { params: { room_type: 'entrance' } })
      .then((res) => setEntrances(res.data.results ?? res.data))
      .catch((err) => console.error('Failed to load entrances', err));
  }, []);

  // ── Fetch building exit rooms ─────────────────────────────────────────────
  useEffect(() => {
    api.get('/rooms/', { params: { room_type: 'building_exit' } })
      .then((res) => setBuildingExits(res.data.results ?? res.data))
      .catch((err) => console.error('Failed to load building exits', err));
  }, []);

  // ── Fetch the user's purchased events that have map coordinates ───────────
  useEffect(() => {
    api.get('/user_events/', { params: { status: 'purchased' } })
      .then((res) => {
        const all: PurchasedEvent[] = res.data.results ?? res.data ?? [];
        setPurchasedEvents(all.filter((e) => resolveEventCoords(e) !== null));
      })
      .catch((err) => console.error('Failed to load purchased events for map', err));
  }, []);

  // ── Auto-resolution: upgrade/downgrade imageZoom as user scrolls ─────────
  useEffect(() => {
    if (leafletZoom == null || leafletCenter == null) return;

    const upgradeThreshold = UPGRADE_AT[imageZoom];
    const downgradeThreshold = DOWNGRADE_AT[imageZoom];

    let newImageZoom: number | null = null;
    if (upgradeThreshold != null && leafletZoom >= upgradeThreshold && imageZoom < 7) {
      newImageZoom = imageZoom + 1;
    } else if (downgradeThreshold != null && leafletZoom <= downgradeThreshold && imageZoom > 3) {
      newImageZoom = imageZoom - 1;
    }

    if (newImageZoom != null) {
      // Save center in Gen Con coords (invariant across imageZoom changes)
      const gc = fromLeafletPos(leafletCenter[0], leafletCenter[1], imgW);
      const newImgW = IMAGE_DIMS[newImageZoom][0];
      // Adjust Leaflet zoom to preserve visual scale: new coordinate space is
      // newImgW/oldImgW times larger, so subtract that from the zoom level.
      const newZoom = leafletZoom - Math.log2(newImgW / imgW);
      savedViewRef.current = { gencon_lng: gc.gencon_lng, gencon_lat: gc.gencon_lat, zoom: newZoom };
      setImageZoom(newImageZoom);
    }
  }, [leafletZoom, imageZoom]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Route fetch ──────────────────────────────────────────────────────────
  useEffect(() => {
    if (!routeFrom || !routeTo) return;
    setRouteResult(null);
    setRouteError(null);
    setRouteLoading(true);
    api.get('/pathfind/', { params: { from: routeFrom.node_id, to: routeTo.node_id } })
      .then((res) => setRouteResult(res.data))
      .catch((err) => {
        const msg = err.response?.data?.error ?? 'Route request failed';
        setRouteError(msg);
      })
      .finally(() => setRouteLoading(false));
  }, [routeFrom, routeTo]);

  // ── Route node selection ──────────────────────────────────────────────────
  const handleRouteNodeClick = (node_id: string, label: string) => {
    if (!routeMode) return;
    if (!routeFrom) {
      setRouteFrom({ node_id, label });
    } else if (!routeTo) {
      setRouteTo({ node_id, label });
    } else {
      // Both set — reset and start fresh
      setRouteFrom({ node_id, label });
      setRouteTo(null);
      setRouteResult(null);
      setRouteError(null);
    }
  };

  const clearRoute = () => {
    setRouteFrom(null);
    setRouteTo(null);
    setRouteResult(null);
    setRouteError(null);
  };

  const handleMapChange = (zoom: number, center: [number, number]) => {
    setLeafletZoom(zoom);
    setLeafletCenter(center);
  };

  const STATIC_URL = import.meta.env.DEV ? 'http://localhost:8000/static' : '/static';

  const [imgW, imgH] = IMAGE_DIMS[imageZoom];
  const bounds: LatLngBoundsExpression = [[-imgH, 0], [0, imgW]];

  const currentFloorNum = parseInt(currentFloor.replace('floor-', ''), 10);

  const mappedVendors = showVendors
    ? vendors.filter(
        (v) => v.map_floor === currentFloorNum || (v.map_floor == null && currentFloorNum === 1),
      )
    : [];

  const mappedEntrances = showEntrances
    ? entrances.filter(
        (r) => r.floor_level === currentFloorNum && r.longitude != null && r.latitude != null,
      )
    : [];

  const mappedExits = showBuildingExits
    ? buildingExits.filter(
        (r) => r.floor_level === currentFloorNum && r.longitude != null && r.latitude != null,
      )
    : [];

  const mappedMyEvents = showMyEvents
    ? purchasedEvents.filter((e) => {
        const coords = resolveEventCoords(e);
        if (!coords) return false;
        // Room-level coords: only show on matching floor
        // Location-level coords (floor=null): show on all floors
        return coords.floor === null || coords.floor === currentFloorNum;
      })
    : [];

  // Rounded zoom for dropdown display
  const displayZoom = leafletZoom != null ? Math.round(leafletZoom) : '';

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 80px)' }}>

      {/* ── Controls bar ──────────────────────────────────────────────────── */}
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          gap: 2,
          px: 2,
          py: 1.5,
          flexShrink: 0,
          bgcolor: 'background.paper',
          borderBottom: `1px solid ${theme.palette.divider}`,
          flexWrap: 'wrap',
        }}
      >
        <FormControl size="small" sx={{ minWidth: 140 }}>
          <InputLabel>Floor</InputLabel>
          <Select
            value={currentFloor}
            label="Floor"
            onChange={(e) => setCurrentFloor(e.target.value)}
          >
            {FLOORS.map((f) => (
              <MenuItem key={f.key} value={f.key}>{f.label}</MenuItem>
            ))}
          </Select>
        </FormControl>

        <FormControl size="small" sx={{ minWidth: 140 }}>
          <InputLabel>Resolution</InputLabel>
          <Select
            value={imageZoom}
            label="Resolution"
            onChange={(e) => setImageZoom(Number(e.target.value))}
          >
            {Object.entries(ZOOM_LABELS).map(([z, label]) => (
              <MenuItem key={z} value={Number(z)}>{label}</MenuItem>
            ))}
          </Select>
        </FormControl>

        {/* ── Map Zoom dropdown ─────────────────────────────────────────── */}
        <FormControl size="small" sx={{ minWidth: 110 }}>
          <InputLabel>Map Zoom</InputLabel>
          <Select
            value={displayZoom}
            label="Map Zoom"
            onChange={(e) => mapRef.current?.setZoom(Number(e.target.value))}
            displayEmpty
          >
            {MAP_ZOOM_STEPS.map((z) => (
              <MenuItem key={z} value={z}>
                {z > 0 ? `+${z}` : z}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <Chip
          icon={<StorefrontIcon fontSize="small" />}
          label={`Vendors (${mappedVendors.length})`}
          color={showVendors ? 'primary' : 'default'}
          variant={showVendors ? 'filled' : 'outlined'}
          onClick={() => setShowVendors((v) => !v)}
          sx={{ cursor: 'pointer' }}
        />

        <Chip
          icon={<MeetingRoomIcon fontSize="small" />}
          label={`Entrances (${mappedEntrances.length})`}
          color={showEntrances ? 'info' : 'default'}
          variant={showEntrances ? 'filled' : 'outlined'}
          onClick={() => setShowEntrances((v) => !v)}
          sx={{ cursor: 'pointer' }}
        />

        <Chip
          icon={<ExitToAppIcon fontSize="small" />}
          label={`Exits (${mappedExits.length})`}
          color={showBuildingExits ? 'error' : 'default'}
          variant={showBuildingExits ? 'filled' : 'outlined'}
          onClick={() => setShowBuildingExits((v) => !v)}
          sx={{ cursor: 'pointer' }}
        />

        <Chip
          icon={<EventIcon fontSize="small" />}
          label={`My Events (${mappedMyEvents.length})`}
          color={showMyEvents ? 'info' : 'default'}
          variant={showMyEvents ? 'filled' : 'outlined'}
          onClick={() => setShowMyEvents((v) => !v)}
          sx={{ cursor: 'pointer', bgcolor: showMyEvents ? '#38bdf8 !important' : undefined, color: showMyEvents ? '#0c1a2e !important' : undefined }}
        />

        <Chip
          icon={<MyLocationIcon fontSize="small" />}
          label="Pick coords"
          color={pickMode ? 'warning' : 'default'}
          variant={pickMode ? 'filled' : 'outlined'}
          onClick={() => { setPickMode((v) => !v); setPicked(null); }}
          sx={{ cursor: 'pointer' }}
        />

        <Chip
          icon={<AltRouteIcon fontSize="small" />}
          label={routeMode ? 'Routing on' : 'Route'}
          color={routeMode ? 'success' : 'default'}
          variant={routeMode ? 'filled' : 'outlined'}
          onClick={() => { setRouteMode((v) => !v); clearRoute(); }}
          sx={{ cursor: 'pointer' }}
        />

        <Typography variant="caption" color="text.secondary" sx={{ ml: 'auto' }}>
          {imgW.toLocaleString()} × {imgH.toLocaleString()} px · scroll to zoom · drag to pan
        </Typography>
      </Box>

      {/* ── Route banner ─────────────────────────────────────────────────── */}
      {routeMode && (
        <Box
          sx={{
            px: 2, py: 1, bgcolor: 'success.dark', color: 'success.contrastText',
            display: 'flex', alignItems: 'center', gap: 2, flexShrink: 0,
            fontFamily: 'monospace', fontSize: 13, flexWrap: 'wrap',
          }}
        >
          <span>
            <strong>From:</strong>{' '}
            {routeFrom ? routeFrom.label : <em style={{ opacity: 0.7 }}>click a pin</em>}
          </span>
          <span style={{ opacity: 0.5 }}>→</span>
          <span>
            <strong>To:</strong>{' '}
            {routeTo ? routeTo.label : <em style={{ opacity: 0.7 }}>{routeFrom ? 'click a pin' : '—'}</em>}
          </span>
          {routeLoading && <span style={{ opacity: 0.7 }}>Calculating…</span>}
          {routeResult && (
            <span style={{ fontWeight: 700 }}>
              {routeResult.total_metres >= 1000
                ? `${(routeResult.total_metres / 1000).toFixed(2)} km`
                : `${routeResult.total_metres} m`}
            </span>
          )}
          {routeError && <span style={{ color: '#fca5a5' }}>{routeError}</span>}
          {(routeFrom || routeTo) && (
            <Typography
              variant="caption"
              sx={{ ml: 'auto', cursor: 'pointer', textDecoration: 'underline' }}
              onClick={clearRoute}
            >
              clear
            </Typography>
          )}
        </Box>
      )}

      {/* ── Coordinate readout (pick mode) ────────────────────────────────── */}
      {pickMode && (
        <Box
          sx={{
            px: 2, py: 1, bgcolor: 'warning.main', color: 'warning.contrastText',
            display: 'flex', alignItems: 'center', gap: 2, flexShrink: 0,
            fontFamily: 'monospace', fontSize: 13,
          }}
        >
          {picked ? (
            <>
              <span>longitude (map_x): <strong>{picked.gencon_lng.toFixed(6)}</strong></span>
              <span>latitude (map_y): <strong>{picked.gencon_lat.toFixed(6)}</strong></span>
              <Typography
                variant="caption"
                sx={{ ml: 'auto', cursor: 'pointer', textDecoration: 'underline' }}
                onClick={() => navigator.clipboard.writeText(
                  `longitude: ${picked.gencon_lng.toFixed(6)}, latitude: ${picked.gencon_lat.toFixed(6)}`
                )}
              >
                copy
              </Typography>
            </>
          ) : (
            <span>Click anywhere on the map to read Gen Con coordinates</span>
          )}
        </Box>
      )}

      {/* ── Map ───────────────────────────────────────────────────────────── */}
      <Box sx={{ flexGrow: 1, position: 'relative', bgcolor: '#0f172a' }}>
        <MapContainer
          key={`${currentFloor}-${imageZoom}`}
          crs={L.CRS.Simple}
          bounds={bounds}
          minZoom={-2}
          scrollWheelZoom={true}
          attributionControl={false}
          zoomControl={true}
          style={{ height: '100%', width: '100%', background: '#0f172a' }}
        >
          <MapEventHandler
            active={pickMode}
            imgW={imgW}
            onPick={setPicked}
            onMapChange={handleMapChange}
            mapRef={mapRef}
            savedViewRef={savedViewRef}
          />

          <ImageOverlay
            url={`${STATIC_URL}/stitched/${currentFloor}_z${imageZoom}.png`}
            bounds={bounds}
            opacity={1}
            zIndex={0}
          />

          {/* Booth outlines */}
          {mappedVendors.map((v) =>
            v.map_polygon ? (
              <Polygon
                key={`poly-${v.gencon_id}`}
                positions={toLeafletPolygon(v.map_polygon, imgW)}
                pathOptions={{ color: '#f59e0b', weight: 1.5, fillColor: '#f59e0b', fillOpacity: 0.12 }}
              />
            ) : null,
          )}

          {/* Vendor pins */}
          {mappedVendors.map((v) => {
            const [lat, lng] = toLeafletPos(v.map_x!, v.map_y!, imgW);
            const pinLabel = v.booth_number ?? v.name.slice(0, 8);
            return (
              <Marker
                key={v.gencon_id}
                position={[lat, lng]}
                icon={vendorIcon(pinLabel)}
                eventHandlers={{ click: () => handleRouteNodeClick(`vendor_${v.id}`, v.name) }}
              >
                <Tooltip direction="top" offset={[0, -4]} opacity={1} className="alpha-vendor-tooltip">
                  <span style={{ fontFamily: 'Inter, Arial, sans-serif', fontSize: 12 }}>
                    <strong>{v.name}</strong>
                    {v.booth_number && <><br />Booth {v.booth_number}</>}
                    {routeMode && <><br /><em style={{ color: '#6ee7b7' }}>click to set route point</em></>}
                  </span>
                </Tooltip>
              </Marker>
            );
          })}

          {/* Entrance pins */}
          {mappedEntrances.map((r) => {
            const [lat, lng] = toLeafletPos(r.longitude!, r.latitude!, imgW);
            const label = entranceLabel(r.room_name);
            return (
              <Marker
                key={r.id}
                position={[lat, lng]}
                icon={entranceIcon(label)}
                eventHandlers={{ click: () => handleRouteNodeClick(`room_${r.id}`, r.room_name) }}
              >
                <Tooltip direction="top" offset={[0, -4]} opacity={1}>
                  <span style={{ fontFamily: 'Inter, Arial, sans-serif', fontSize: 12 }}>
                    <strong>{r.room_name}</strong>
                    {routeMode && <><br /><em style={{ color: '#6ee7b7' }}>click to set route point</em></>}
                  </span>
                </Tooltip>
              </Marker>
            );
          })}

          {/* Building exit pins */}
          {mappedExits.map((r) => {
            const [lat, lng] = toLeafletPos(r.longitude!, r.latitude!, imgW);
            const label = buildingExitLabel(r.room_name);
            return (
              <Marker
                key={`exit-${r.id}`}
                position={[lat, lng]}
                icon={buildingExitIcon(label)}
                eventHandlers={{ click: () => handleRouteNodeClick(`room_${r.id}`, r.room_name) }}
              >
                <Tooltip direction="top" offset={[0, -4]} opacity={1}>
                  <span style={{ fontFamily: 'Inter, Arial, sans-serif', fontSize: 12 }}>
                    <strong>{r.room_name}</strong>
                    {routeMode && <><br /><em style={{ color: '#fca5a5' }}>click to set route point</em></>}
                  </span>
                </Tooltip>
              </Marker>
            );
          })}

          {/* Purchased event pins */}
          {mappedMyEvents.map((ev) => {
            const coords = resolveEventCoords(ev)!;
            const [lat, lng] = toLeafletPos(coords.lng, coords.lat, imgW);
            // Shorten the title for the pin label (first ~18 chars)
            const pinLabel = ev.event_title.length > 20 ? ev.event_title.slice(0, 18) + '…' : ev.event_title;
            const startTime = new Date(ev.event_start_time).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
            return (
              <Marker
                key={`my-event-${ev.id}`}
                position={[lat, lng]}
                icon={myEventIcon(pinLabel)}
                zIndexOffset={1000}
                eventHandlers={{ click: () => handleRouteNodeClick(`event_${ev.id}`, ev.event_title) }}
              >
                <Tooltip direction="top" offset={[0, -4]} opacity={1} className="alpha-event-tooltip">
                  <span style={{ fontFamily: 'Inter, Arial, sans-serif', fontSize: 12 }}>
                    <strong>{ev.event_title}</strong>
                    <br />
                    {ev.event_location}{ev.event_room ? ` · ${ev.event_room}` : ''}
                    <br />
                    <span style={{ color: '#9ca3af' }}>{startTime}</span>
                    {coords.floor === null && <><br /><span style={{ color: '#f59e0b', fontSize: 10 }}>📍 building-level pin</span></>}
                    {routeMode && <><br /><em style={{ color: '#6ee7b7' }}>click to set route point</em></>}
                  </span>
                </Tooltip>
              </Marker>
            );
          })}

          {/* Route polylines */}
          {routeResult?.segments.map((seg, i) => {
            if (seg.from_lng == null || seg.from_lat == null || seg.to_lng == null || seg.to_lat == null) return null;
            const from = toLeafletPos(seg.from_lng, seg.from_lat, imgW);
            const to   = toLeafletPos(seg.to_lng,   seg.to_lat,   imgW);
            const color = seg.edge_type === 'outdoor' ? '#ea580c'
                        : seg.edge_type === 'exterior' ? '#f97316'
                        : '#f59e0b';
            return (
              <Polyline
                key={`route-seg-${i}`}
                positions={[from, to]}
                pathOptions={{ color, weight: 5, opacity: 0.85, dashArray: seg.edge_type === 'outdoor' ? '8 6' : undefined }}
              />
            );
          })}
        </MapContainer>
      </Box>
    </Box>
  );
}
