# Generated by Django 5.2.1 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_attendees_remove_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobility_aid',
            field=models.CharField(choices=[('none', 'No Issues'), ('wheelchair', 'Wheelchair'), ('cane', 'Cane'), ('walker', 'Walker'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='stair_preference',
            field=models.CharField(choices=[('stairs', 'Prefer Stairs'), ('elevator', 'Prefer Elevator'), ('no_preference', 'No Preference')], default='no_preference', max_length=20),
        ),
    ]
