# Generated by Django 5.2.1 on 2025-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules_edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
