# Generated by Django 5.2.1 on 2025-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_game_id_alter_event_rules_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
