# Generated by Django 5.2.1 on 2025-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_event_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gm_names',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
