# Generated by Django 5.2.1 on 2025-05-22 20:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_location_base_latitude_location_base_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobility_aid',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'No Issues'), ('wheelchair', 'Wheelchair'), ('cane', 'Cane'), ('walker', 'Walker'), ('other', 'Other')], default='none', max_length=33),
        ),
    ]
