# Generated by Django 5.2.1 on 2025-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_mobility_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_code',
            field=models.CharField(choices=[('#00F0FF', 'Electric Blue'), ('#00FF81', 'Green'), ('#FFA900', 'Orange'), ('#FF6800', 'Pumpkin'), ('##6F2DBD', 'Purple')], default='#00F0FF', max_length=24),
        ),
    ]
