# Generated by Django 5.2.1 on 2025-06-05 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(choices=[('#00F0FF', 'Electric Blue'), ('#00FF81', 'Green'), ('#FFA900', 'Orange'), ('#FF6800', 'Pumpkin'), ('#6F2DBD', 'Purple')], default='#00F0FF', max_length=24)),
                ('relationship', models.CharField(choices=[('son', 'Son'), ('father', 'Father'), ('friend', 'Friend')], default='friend', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userevent',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.relateduser'),
        ),
    ]
