# Generated by Django 5.2.1 on 2025-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_relateduser_userevent_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relateduser',
            name='color_code',
            field=models.CharField(choices=[('#00F0FF', 'Blue'), ('#00FF81', 'Green'), ('#FFA900', 'Orange'), ('#FF6800', 'Pumpkin'), ('#6F2DBD', 'Purple')], default='#00F0FF', max_length=24),
        ),
        migrations.AlterField(
            model_name='relateduser',
            name='relationship',
            field=models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('spouse', 'Spouse'), ('partner', 'Partner'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('friend', 'Friend')], default='friend', max_length=20),
        ),
    ]
