# Generated by Django 5.2.1 on 2025-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_relateduser_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='related_user',
        ),
        migrations.AddField(
            model_name='userevent',
            name='related_users',
            field=models.ManyToManyField(blank=True, to='app.relateduser'),
        ),
    ]
