# Generated by Django 5.2.1 on 2025-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_userevent_related_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='self_assigned',
            field=models.BooleanField(default=True),
        ),
    ]
