# Generated by Django 5.2.1 on 2025-06-12 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userevent_self_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gencon_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('booth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='color_code',
            field=models.CharField(choices=[('#00F0FF', 'Blue'), ('#00FF81', 'Green'), ('#FFA900', 'Orange'), ('#FF6800', 'Pumpkin'), ('#6F2DBD', 'Purple')], default='#00F0FF', max_length=24),
        ),
        migrations.CreateModel(
            name='UserVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vendors', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vendors', to='app.vendor')),
            ],
            options={
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
