# Generated by Django 5.2.1 on 2025-06-12 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_vendor_alter_user_color_code_uservendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gencon_event_id', models.CharField(max_length=32)),
                ('last_known_status', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gencon_event_id')},
            },
        ),
    ]
