# Generated by Django 5.2.1 on 2025-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userwatchedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('board_games', 'Board Games'), ('card_games', 'Card Games'), ('roleplaying_games', 'Roleplaying Games'), ('miniatures', 'Miniatures'), ('wargames', 'Wargames'), ('game_accessories', 'Game Accessories'), ('dice', 'Dice'), ('game_mats', 'Game Mats'), ('larp_gear', 'LARP Gear'), ('art', 'Art'), ('prints', 'Prints'), ('original_artwork', 'Original Artwork'), ('comics', 'Comics'), ('fantasy_art', 'Fantasy Art'), ('3d_printing', '3D Printing'), ('sculptures', 'Sculptures'), ('fan_art', 'Fan Art'), ('tshirts', 'T-Shirts'), ('cosplay', 'Cosplay'), ('pins_patches', 'Pins & Patches'), ('jewelry', 'Jewelry'), ('hats_headwear', 'Hats & Headwear'), ('bags', 'Bags'), ('handmade_goods', 'Handmade Goods'), ('candles', 'Candles'), ('dice_trays', 'Dice Trays'), ('woodworking', 'Woodworking'), ('leather_goods', 'Leather Goods'), ('resin_crafts', 'Resin Crafts'), ('novels', 'Novels'), ('indie_authors', 'Indie Authors'), ('zines', 'Zines'), ('demos', 'Demos'), ('workshops', 'Workshops'), ('custom_commissions', 'Custom Commissions'), ('streaming_content', 'Streaming & Content Creation')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='app.tag'),
        ),
    ]
