# Generated by Django 5.2.1 on 2025-06-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_tag_insertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='booth_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
