# Generated by Django 5.2.1 on 2025-06-27 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_tag_options_alter_vendor_options_vendorvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorvisit',
            name='scheduled_event',
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('gencon_event', 'GenCon Event'), ('vendor_visit', 'Vendor Visit'), ('custom', 'Custom Event')], max_length=20)),
                ('title_override', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('gencon_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('vendor_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vendorvisit')),
            ],
        ),
    ]
