# Generated by Django 5.2.1 on 2025-06-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_vendorvisit_scheduled_event_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='user_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='app.userevent'),
        ),
    ]
