# Generated by Django 5.2.1 on 2025-07-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_calendarevent_user_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatchedevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userwatchedevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='app.event', to_field='game_id'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_links', to='app.event'),
        ),
        migrations.AlterField(
            model_name='userwatchedevent',
            name='gencon_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchedevent',
            unique_together={('user', 'event')},
        ),
    ]
