# Generated by Django 5.2.1 on 2025-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20250718_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_guest_exhibitor',
            field=models.BooleanField(default=False),
        ),
    ]
