# Generated by Django 5.2.1 on 2025-07-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_vendor_is_guest_exhibitor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('location', 'room_name')},
        ),
    ]
