# Generated by Django 4.2.11 on 2026-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gencon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
