# Generated by Django 4.2.11 on 2026-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_user_gencon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gencon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
