# Generated by Django 4.2.11 on 2026-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_user_gencon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw',
            field=models.JSONField(default=False),
        ),
    ]
