# Generated by Django 4.2.11 on 2026-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_event_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
