# Generated by Django 4.2.11 on 2026-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='raw',
            field=models.JSONField(default=dict),
        ),
    ]
