# Generated by Django 4.2.11 on 2026-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_event_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='makers_market',
            field=models.BooleanField(default=False),
        ),
    ]
