# Generated by Django 4.2.11 on 2026-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_vendor_makers_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relateduser',
            name='color_code',
            field=models.CharField(choices=[('#f59e0b', 'Amber'), ('#fb923c', 'Orange'), ('#f87171', 'Rose'), ('#818cf8', 'Indigo'), ('#a78bfa', 'Violet'), ('#34d399', 'Emerald'), ('#38bdf8', 'Sky')], default='#f59e0b', max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='color_code',
            field=models.CharField(choices=[('#f59e0b', 'Amber'), ('#fb923c', 'Orange'), ('#f87171', 'Rose'), ('#818cf8', 'Indigo'), ('#a78bfa', 'Violet'), ('#34d399', 'Emerald'), ('#38bdf8', 'Sky')], default='#f59e0b', max_length=24),
        ),
    ]
