# Generated by Django 4.2.11 on 2026-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_relateduser_color_code_alter_user_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='map_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
