# Generated by Django 4.2.11 on 2026-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_vendor_map_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='map_polygon',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
